version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nx-elasticaudit-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ELASTICSEARCH_URL=http://10.52.1.17:9200
      - ELASTICSEARCH_INDEX=nuxeo2023-audit
    ports:
      - "3000:3000"
    networks:
      - nx-elasticaudit-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nx-elasticaudit-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - nx-elasticaudit-network
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  nx-elasticaudit-network:
    driver: bridge
